---
title: "Grim Tallies"
author: The Economist
date: September, 2020
output: github_document
---

This repository provides data and code for the briefing "Grim Tallies". 

Our scripts are written in R and available in the folder "scripts". Our data is contained in the folder "source-data".

### Excess mortality
Our excess mortality data and code is available in [this repo.](https://github.com/TheEconomist/covid-19-excess-deaths-tracker).


### SEIR models
For more information on such simulations and how they work, see: https://www.idmod.org/docs/emod/hiv/model-seir.html

For the purposes of the simulations featured in the briefing, we based our parameters for COVID-19 on [Ferretti et al (2020)](https://www.medrxiv.org/content/10.1101/2020.09.04.20188516v2) as well the [OpenABM-Covid19 parameters](https://github.com/BDI-pathogens/OpenABM-Covid19/blob/master/tests/data/baseline_parameters_transpose.csv). To account for vaccination taking time to scale, we assumed only 1m could be vaccinated in the first month of vaccinations. 


### Licence
This software is published by _[The Economist](https://www.economist.com)_ under the [MIT licence](https://opensource.org/licenses/MIT). The data generated by _The Economist_ are available under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).
The licences include only the data and the software authored by _The Economist_, and do not cover any _Economist_ content or third-party data or content made available using the software. More information about licensing, syndication and the copyright of _Economist_ content can be found [here](https://www.economist.com/rights/).